### ISSUE TITLE
calculator returns incorrect results

### ISSUE THREAD

**Issue by schirmacher** [arothuis/antlr4-calculator#1]
I tested your calculator with the inputs below:

    Calculate: 1-2
    -1.0
    Calculate: 1-2*3
    -5.0
    Calculate: 1-2*3+4
    -9.0

This is wrong, 1-2*3+4 = -1.0

**Comment by arothuis** [comment]
I only read this yesterday. Nice catch!

Fixed the grammar and I was inspired to restructure the application and add some tests.
