### ISSUE TITLE
Questions about how to build locally in Intellij IDEA

### ISSUE THREAD

**Issue by Hongzheng369** [arothuis/antlr4-calculator#2]
Hi,

Sorry to interrupt. Could you help me how to build this project in Intellij IDEA locally? 

```
import nl.arothuis.antlr4calculator.core.parser.CalculatorLexer;
import nl.arothuis.antlr4calculator.core.parser.CalculatorParser;
```
It suggests that these two classes cannot be imported.

**Comment by arothuis** [comment]
Hi there! I'm sure you already found your answer, but I'll update this repository anyways.

This is a good question, and I needed to look up the answer myself!

Thanks for the issue! I have added the following to the README:
* Make sure your IDE includes the generated-sources in its imports.
    * In IntelliJ IDEA, you can right-click the project folder at the top of the project tab (in our case `antlr4-calculator`)
      and then click `Maven > Generate Sources and Update Folders`

Keep in mind that this is an (old) example project to show how to use antlr4, so it might not be suitable for anything other than that.
