### ISSUE TITLE
Sub operator not work 

### ISSUE THREAD

**Issue by gprsphone** [arothuis/antlr4-calculator#3]
Start program with 'nl.arothuis.antlr4calculator.ListenerMain'  or 'nl.arothuis.antlr4calculator.ListenerMain'
Calculate: 4-2
        4.0
Calculate: 4+-2
        2.0

This may due to "-" is treated as number, but how to fix it?

**Comment by arothuis** [comment]
This issue has been resolved by #4. 
Sorry for the long wait.
